### ISSUE TITLE
IDE 0.15.1 crashes at startup in Windows

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#179]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=144) by teme.temppuilija on 27 May 2009*

I was not able to run IDE 0.15.1. 0.14 is running fine. I have Python 2.6
in use. 

I got following stack trace:

Traceback (most recent call last):
  File "c:\python26\lib\runpy.py", line 121, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python26\lib\runpy.py", line 34, in _run_code
    exec code in run_globals
  File "c:\python26\lib\site-packages\robotide\run.py", line 22, in &lt;module&gt;
    main(sys.argv[1:])
  File "C:\Python26\Lib\site-packages\robotide\__init__.py", line 47, in main
    _run(*args)
  File "C:\Python26\Lib\site-packages\robotide\__init__.py", line 57, in _run
    from robotide.layout import RobotIde
  File "C:\Python26\Lib\site-packages\robotide\layout\__init__.py", line 15, in
&lt;module&gt;
    from application import RobotIde
  File "C:\Python26\Lib\site-packages\robotide\layout\application.py", line 18,
in &lt;module&gt;
    from robotide import context
  File "C:\Python26\Lib\site-packages\robotide\context\__init__.py", line
15, in
 &lt;module&gt;
    from cache import LibraryCache
  File "C:\Python26\Lib\site-packages\robotide\context\cache.py", line 15,
in &lt;m
odule&gt;
    from robotide.spec import LibrarySpec
  File "C:\Python26\Lib\site-packages\robotide\spec\__init__.py", line 15,
in &lt;m
odule&gt;
    from spec import LibrarySpec, XMLResource, UserKeywordContent
  File "C:\Python26\Lib\site-packages\robotide\spec\spec.py", line 17, in
&lt;modul
e&gt;
    from robotide.robotapi import TestLibrary as RobotTestLibrary
  File "C:\Python26\Lib\site-packages\robotide\robotapi.py", line 19, in
&lt;module
&gt;
    from robot.output import LOGGER as ROBOT_LOGGER
ImportError: cannot import name LOGGER

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=144#c1) by @pekkaklarck on 27 May 2009*


Do you have Robot Framework 2.1 or some older? This version only works with RF 2.1.
RIDE should give a better error message with older RF versions in any case.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=144#c2) by teme.temppuilija on 27 May 2009*


Ok. In that case it should be noted at some page. I have 2.0.something because I
don't have time to upgrade the libraries and risk the working tests.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=144#c3) by @pekkaklarck on 27 May 2009*


Requirement for RF 2.1 is mentioned on 0.15 release notes. In a retrospect that note
should be on bold or otherwise more visible and this should've been mentioned also on
the release mail. I'll update the wiki page and we'll probably send a separate mail
to rf-users about this. Thanks for bringing this to our attention.
