### ISSUE TITLE
Select All Tests doesn't work in WinXP

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#1165]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1126) by c.martin.taylor on 20 Nov 2012*

On a WinXP Professional Version 2002, Service Pack 3 system running on an Intel Core2 Duo CPU T7500 @&#8288; 2.20 GHz with2 GB RAM, with RIDE 0.53, if you right-click on a test suite in the tree view and select "Select All Tests", the CMD window where RIDE was launched shows the following error messages:

Traceback (most recent call last):
  File "C:\Python26\lib\site-packages\robotide\ui\treenodehandlers.py", line 128
, in OnSelectAllTests
    self._tree.SelectAllTests(self._node)
  File "C:\Python26\lib\site-packages\robotide\ui\tree.py", line 590, in SelectA
llTests
    self._for_all_tests(item, lambda t: self.CheckItem(t))
  File "C:\Python26\lib\site-packages\robotide\ui\tree.py", line 605, in _for_al
l_tests
    if not self.HasAGWFlag(customtreectrl.TR_HIDE_ROOT) or item != self.GetRootI
tem():
AttributeError: 'Tree' object has no attribute 'HasAGWFlag'

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1126#c1) by c.martin.taylor on 20 Nov 2012*


The same bug happens on a MacBook Pro, core i7, running OS X 10.7.4.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1126#c2) by @mkorpela on 20 Nov 2012*


Seems like you have an old version of wxpython.

What version of wxpython are you using?

Could you try to update it.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1126#c3) by @mkorpela on 28 Nov 2012*


Seems to work with wxpython 2.8.11 but not 2.8.10.

We need to decide what is the minimum wxpython version before 1.0.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1126#c4) by c.martin.taylor on 28 Nov 2012*


Updated my WinXP machine to wxPython 2.8.12.1 and the problem goes away. Will try the same with my Mac.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1126#c5) by c.martin.taylor on 28 Nov 2012*


Works fine on Mac, too, with wxPython 2.8.12.1.
