### ISSUE TITLE
Rename error when renaming KW

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#1037]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=998) by c.martin.taylor on 29 Jun 2012*

I tried right-click and Rename on a Keyword in a Resource file. RIDE froze and the CMD window where it was launched showed:

Traceback (most recent call last):
  File "C:\Python26\lib\site-packages\robotide\ui\tree.py", line 690, in OnLeftDown
    self._tree.OnCancelEdit(self._tree.GetSelection())
AttributeError: 'Tree' object has no attribute 'OnCancelEdit'

This was on Windows 7 with RIDE 0.45.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=998#c1) by c.martin.taylor on 29 Jun 2012*


Same error happened when trying to rename a Test Case in a Suite:
Traceback (most recent call last):
  File "C:\Python26\lib\site-packages\robotide\ui\tree.py", line 690, in OnLeftDown
    self._tree.OnCancelEdit(self._tree.GetSelection())
AttributeError: 'Tree' object has no attribute 'OnCancelEdit'

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=998#c2) by @jussimalinen on 2 Jul 2012*


I am unable to reproduce this. Does this still happen with 0.46?

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=998#c3) by @jussimalinen on 2 Jul 2012*


Also, if this still happens on 0.46, could you post your wx version? (printed on your ride log at start)

I am making a new version tomorrow, so unless I am able to reproduce this somehow, this will get moved to a later release...

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=998#c4) by c.martin.taylor on 4 Jul 2012*


Sorry I didn't see this request before 0.46.1 came out.  I'm now running RIDE 0.46.1.  I couldn't find this issue for some reason yesterday and thought maybe I hadn't raised it, so I raised new <a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=1003" title="Test Case Rename does not work"> issue 1003 </a>, which should be duplicated to this one.

My RIDE log shows: AAARRRGGG! Can't copy and paste 'cause that RIDE functionality is broken in Mac OSX!
Hand typing the relevant part... wx version 2.8.10.1

The bash shell window where I start RIDE also shows this message:  2012-07-04 10:51:37.109 Python[54185:60b] CFURLCreateWithString was passed this invalid URL string: '/System/Library/CoreServices/CommonCocoaPanels.bundle' (a file system path instead of an URL string). The URL created will not work with most file URL functions. CFURLCreateWithFileSystemPath or CFURLCreateWithFileSystemPathRelativeToBase should be used instead.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=998#c5) by @jussimalinen on 11 Jul 2012*


Also unbale to reproduce this on osx. Does it change things if you update your wx?

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=998#c6) by jerry57 on 20 Jul 2012*


I have tried this on Mac OS X 10.6 and 10.7, python 2.7 and 2.6, wx versions 2.8.8.1 and 2.8.12.1 (mac-ansi).  In order to rename keywords, testcases etc... you have to right click, select rename, right click, select rename twice before it will allow renaming.  Copy/Paste/Cut is broken totally as well on all of the above versions.  The wx 2.8.12.1 is the latest available for python 2.7 on Lion.  I have tried both unicode and ansi with same results.  Version 2.9 isn't supported by right yet, separate issue already filed.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=998#c7) by aalto.tatu on 15 Aug 2012*


I get a similar error when using windows 7 and doing the rename as in the first post: 
C:\Users\xxx&gt;ride.py
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\robotide\ui\tree.py", line 720, in OnLabelEdited
    wx.CallAfter(wx.CallAfter, self._tree.ResetEditControl)
AttributeError: 'Tree' object has no attribute 'ResetEditControl'

This is from the log window: 
20120815 16:54:06.170 [INFO]: Started RIDE 0.47.messagelog using python version 2.7.2 with wx version 2.8.12.0.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=998#c10) by aalto.tatu on 7 Sep 2012*


When hunting for some other problem, I did sumble to a point where this error starts to show: 
1) Fisrt I did this:
git clone git://github.com/robotframework/RIDE.git
cd RIDE
git checkout 0.48
git bisect reset
git bisect start
git checkout 0.48
git bisect bad
git checkout 0.41
2) Here is detailled log, what did happen next: 
C:\workspace\ride\RIDE&gt;paver run
---&gt; pavement.run

C:\workspace\ride\RIDE&gt;git bisect good
Bisecting: 221 revisions left to test after this (roughly 8 steps)
[<a href="https://code.google.com/p/robotframework-ride/source/detail?r=04d60ed4dc48c6d8cd43396d0e5386b70a8ec265">04d60ed4dc48c6d8cd43396d0e5386b70a8ec265</a>] Merge branch 'master' of <a href="https://github.com/robotframework/RIDE" rel="nofollow">https://github.com/robotframework/RIDE</a>

C:\workspace\ride\RIDE&gt;paver run
---&gt; pavement.run

C:\workspace\ride\RIDE&gt;git bisect good
Bisecting: 110 revisions left to test after this (roughly 7 steps)
[<a href="https://code.google.com/p/robotframework-ride/source/detail?r=ee7bdc54dc604868beb7295bb06ac246bc8df3e6">ee7bdc54dc604868beb7295bb06ac246bc8df3e6</a>] change run plugin to use subprocess, thread and queue instead of wx.Process in order to use cwd when runnin
g

C:\workspace\ride\RIDE&gt;paver run
---&gt; pavement.run

C:\workspace\ride\RIDE&gt;paver run
---&gt; pavement.run
Traceback (most recent call last):
  File "src\robotide\ui\tree.py", line 700, in OnLeftDown
    self._tree.OnCancelEdit(self._tree.GetSelection())
AttributeError: 'Tree' object has no attribute 'OnCancelEdit'

C:\workspace\ride\RIDE&gt;

The prosedure to produce the problem is same as decscribed in the first post.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=998#c11) by @mkorpela on 7 Sep 2012*


Hi Tatu,

You need to hunt for a little bit more.
Bisecting: 110 revisions left to test after this (roughly 7 steps)
2^7 = 128 (&gt; 110)

You have discovered a bad version after two good versions but the goal is to find the first version (from those 110 revisions between the currently discovered good and bad version) where the problem starts to occur.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=998#c13) by @Tattoo on 6 Nov 2012*


<a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=1003" title="Test Case Rename does not work"> Issue 1003 </a> has been merged into this issue.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=998#c15) by @mikahanninen on 12 Nov 2012*


Checked with latest RIDE on OSX, Linux and Windows 7, and could not reproduce this anymore. Closed
