### ISSUE TITLE
recentfiles plugin blocks startup after upgrade to v2.2.1.1

### ISSUE THREAD

**Issue by JFoederer** [robotframework/RIDE#2998]
After upgrading to RIDE v2.2.1.1 it doesn't startup anymore

Running from command line reveals this logging:
```
'Plugins'
'Plugins'
Traceback (most recent call last):
  File "C:\Users\...\Python313\Lib\site-packages\robotide\application\application.py", line 131, in OnInit
    self.workspace_path = self.workspace_path or self._get_latest_path()
                                                 ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\...\Python313\Lib\site-packages\robotide\application\application.py", line 476, in _get_latest_path
    recent = self._get_recentfiles_plugin()
  File "C:\Users\...\Python313\Lib\site-packages\robotide\application\application.py", line 487, in _get_recentfiles_plugin
    if isinstance(pl.conn_plugin, RecentFilesPlugin):
                  ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'conn_plugin'
OnInit returned false, exiting...
```

**Comment by HelioGuilherme66** [comment]
Fixed in v2.2.2dev2

**Comment by JFoederer** [comment]
Fix confirmed
